export const FETCHING_USERS_DATA = 'FETCHING_USERS_DATA';
export const FETCHING_USERS_DATA_SUCCESS = 'FETCHING_USERS_DATA_SUCCESS';
export const FETCHING_USERS_DATA_FAIL = 'FETCHING_USERS_DATA_FAIL';
